### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by fredstro**
This doesn't really fix anything obvious but hopefully shouldn't break anything either...

### CODE REVIEW

**Comment by JohnCremona** [comment]
I don't want to merge this since it introduces 2 errors and 5 failures in test_emf.py, which are not trivial but signs of something more serious, including runtime errors:

File "/home/jec/lmfdb/lmfdb/modular_forms/elliptic_modular_forms/backend/web_object.py", line 307, in **init**
    raise RuntimeError(str(e))
RuntimeError: 'unicode' object has no attribute 'absolute_degree'

I think the best way to sort this out would be for you to merge with my refactor branch on your side and fix these, then update your branch.  Please?

**Comment by JohnCremona** [comment]
Thanks, just testing now...

**Comment by JohnCremona** [comment]
Do you know why ModularForm/GL2/Q/holomorphic/2/2/1/ produces no data ("Unfortunately, we do not have this space in the database, yet.") ?

**Comment by sehlen** [comment]
It's a data problem, unfortunately.

**Comment by sehlen** [comment]
It is solved now for this space but still not for all spaces.

**Comment by JohnCremona** [comment]
OK, so as it is a data problem I will merge this, and push everything we now have to master and to beta.

**Pull request merged**
