### PR TITLE
Hmf conjugates bugfix

### PR DESCRIPTION
**Pull request by AurelPage**
This should fix the issue with the field '6.6.905177.1'. You can now build the conjugate forms without adding them with checkadd_conj(fldlabel, buildform=True), which did not work in 08c7b4b202b40dbcdcdb3 but is fixed in the last commit.

Update: this updated pull-request contains the code having the correct behaviour for forms that are base-change but not from Q, and implements check_multiplicity_one

### CODE REVIEW

**Comment by JohnCremona** [comment]
I merged current master into my own hmf-conjugates branch which caused this pull request to automatically update to show the changes from that, which looks a lot simpler -- but also introduced some merge conflicts.  I'm not sure I will get to looking into this today.

**Comment by AurelPage** [comment]
Will be replaced with another pull request.

**Comment by AurelPage** [comment]
Let's see if we can merge now.

**Comment by JohnCremona** [comment]
I think we should not put the passwords into files under git control.  I started and nearly finished a system where the usernames and passwords are in a yaml file and read in by the code, but that branch is on at kings  and I only have a tablet to use so cannot push it here.  No hurry.

**Comment by AurelPage** [comment]
I agree, but we will need to change the current password anyways, because there are already commits in master in which the password is hard-coded in some files. So it does not hurt to merge more commits that have it, as long as we change it once it is not hard-coded anywhere anymore.

**Comment by JohnCremona** [comment]
On 7 Nov 2015 15:10, "AurelPage" notifications@github.com wrote:

> I agree, but we will need to change the current password anyways, because
> there are already commits in master in which the password is hard-coded in
> some files. So it does not hurt to merge more commits that have it, as long
> as we change it once it is not hard-coded anywhere anymore.

Fair enough.  I managed to make a commit on atkin but cannot push to github
because I have not yet worked out how to get ssh authentication forwarding
working.

John

**Comment by JohnCremona** [comment]
I will resolve the conflicts (sorry, I caused more...)

**Comment by JohnCremona** [comment]
OK, I did the merge locally so the branch hmf-conjugates does have the changes in this pull request.  So I am closing, not merging it.

**Pull request closed without merging**
